#!/usr/bin/env zsh
snoot="$1"

if [[ ! "$snoot" =~ "^\w+$" ]]; then
	echo "hey, snoots are words!"
	exit 10
fi

if [ ! -e "/www/snoot.club/snoots/$snoot/" ]; then
	echo "hey $snoot is no snoot!!"
	exit 22
fi

awk -F: '/127.0.0.1/ { sub("/;","",$3); print $3}' /www/snoot.club/snoots/$snoot/nginx.conf

