#!/bin/sh
Snoot="$1"
Snoot_Root="/www/snoot.club/snoots"

cd "$Snoot_Root"

Existing_User="$(</etc/passwd awk -F: '{print $1}' | grep -e "^$Snoot\$")"

if [ -z "$Existing_User" ]; then
	echo
	echo creating user
	echo

	sudo useradd -m -d "/snoots/$Snoot" -g common -G common,undercommon -s /bin/nologin "$Snoot"
else
	echo
	echo user "$Snoot" existed m8, hope that\'s ok\!
	echo
fi

echo enter their github username pls

read -r $Github_Username

echo
echo creating authorized_keys file on host
echo

sudo mkdir -p "/snoots/$Snoot/.ssh"
sudo sh -c "curl https://github.com/$Github_Username.keys >> /snoots/$Snoot/.ssh/authorized_keys"
sudo chmod -R 755 "/snoots/$Snoot/.ssh"
sudo chown -R root.root "/snoots/$Snoot/.ssh"

echo
echo containing snoot
echo

/www/snoot.club/contain_snoot "$Snoot" "$Public_Key"

sudo chown -R "$Snoot.common" "$Snoot_Root/$Snoot/application/website"

echo
echo binding snoots
echo

/www/snoot.club/bind_snoots

echo
echo reloading nginx
echo

sudo nginx -s reload
