#!/bin/sh
cd /www/snoot.club/snoots
for snoot in *; do
	real="/www/snoot.club/snoots/$snoot/application/website"
	pretend="/snoots/$snoot/website"
	sudo mkdir -p "$pretend"
	sudo umount "$pretend" 2>/dev/null
	[ -e "$real" ] && sudo mount --bind "$real" "$pretend"
	sudo chown root.root "/snoots/$snoot"
	sudo chmod 755 "/snoots/$snoot"
done
